---
driver:
  name: vagrant

provisioner:
  name: ansible_playbook

platforms:
  - name: ubuntu-14.04
  - name: centos-7.1
  - name: centos-7.2
    #  - name: centos-7.3

suites:
  - name: default
    run_list:
    attributes:
